In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,ElasticNet

In [2]:
df=pd.read_excel(r"C:\Users\CHAIT\OneDrive\Desktop\TE\Machine Learning\Dataset\Supervised\demo\elastic_net_demo_dataset.xlsx")
df.head()

,Employee_ID,Age,Years_Experience,Education,City,Department,Projects_Completed,Training_Hours,Performance_Rating,Job_Satisfaction,Overtime,Annual_Salary,Annual_Bonus
0,1,28,7,M.Tech,Mumbai,Sales,3,3,4.03,4.57,0,670198,52852
1,2,23,2,B.Tech,Mumbai,Sales,9,19,2.08,1.80,1,423446,40170
2,3,38,17,B.Sc,Nagpur,HR,5,4,2.65,4.05,0,1045578,49707
3,4,27,4,M.Tech,Aurangabad,HR,13,1,4.19,3.14,1,603664,45743
4,5,39,13,MBA,Nashik,Marketing,4,2,2.14,1.91,1,801230,46120

In [3]:
df=df.drop(columns=['Employee_ID','City'],axis=1)

In [4]:
df.head()

,Age,Years_Experience,Education,Department,Projects_Completed,Training_Hours,Performance_Rating,Job_Satisfaction,Overtime,Annual_Salary,Annual_Bonus
0,28,7,M.Tech,Sales,3,3,4.03,4.57,0,670198,52852
1,23,2,B.Tech,Sales,9,19,2.08,1.80,1,423446,40170
2,38,17,B.Sc,HR,5,4,2.65,4.05,0,1045578,49707
3,27,4,M.Tech,HR,13,1,4.19,3.14,1,603664,45743
4,39,13,MBA,Marketing,4,2,2.14,1.91,1,801230,46120

In [5]:
df["Education"].describe()

count        200
unique         5
top       M.Tech
freq          48
Name: Education, dtype: object

In [6]:
df["Department"].describe()

count     200
unique      5
top        HR
freq       47
Name: Department, dtype: object

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
one=OneHotEncoder(sparse_output=False)

In [9]:
encode=one.fit_transform(df[['Education','Department']])

In [10]:
print(encode)

[[0. 0. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]

In [11]:
encoded_df=pd.DataFrame(encode,columns=one.get_feature_names_out(['Education','Department']))
encoded_df

,Education_B.Sc,Education_B.Tech,Education_M.Tech,Education_MBA,Education_MCA,Department_Finance,Department_HR,Department_IT,Department_Marketing,Department_Sales
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
195,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
196,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
197,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
198,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
199,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [12]:
df=pd.concat([df,encoded_df],axis=1)

In [13]:
df.head()

,Age,Years_Experience,Education,Department,Projects_Completed,Training_Hours,Performance_Rating,Job_Satisfaction,Overtime,Annual_Salary,...,Education_B.Sc,Education_B.Tech,Education_M.Tech,Education_MBA,Education_MCA,Department_Finance,Department_HR,Department_IT,Department_Marketing,Department_Sales
0,28,7,M.Tech,Sales,3,3,4.03,4.57,0,670198,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,23,2,B.Tech,Sales,9,19,2.08,1.80,1,423446,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,38,17,B.Sc,HR,5,4,2.65,4.05,0,1045578,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,27,4,M.Tech,HR,13,1,4.19,3.14,1,603664,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,39,13,MBA,Marketing,4,2,2.14,1.91,1,801230,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [14]:
df=df.drop(['Education','Department'],axis=1)

In [15]:
df.head()

,Age,Years_Experience,Projects_Completed,Training_Hours,Performance_Rating,Job_Satisfaction,Overtime,Annual_Salary,Annual_Bonus,Education_B.Sc,Education_B.Tech,Education_M.Tech,Education_MBA,Education_MCA,Department_Finance,Department_HR,Department_IT,Department_Marketing,Department_Sales
0,28,7,3,3,4.03,4.57,0,670198,52852,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,23,2,9,19,2.08,1.80,1,423446,40170,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,38,17,5,4,2.65,4.05,0,1045578,49707,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,27,4,13,1,4.19,3.14,1,603664,45743,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,39,13,4,2,2.14,1.91,1,801230,46120,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [16]:
x=df.drop(columns=['Annual_Bonus'],axis=1)

In [17]:
y=df['Annual_Bonus']

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [20]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [21]:
le=LinearRegression()
le.fit(x_train,y_train)

LinearRegression()

In [22]:
y_pred = le.predict(x_test)

print("MSE =", mean_squared_error(y_test, y_pred))
print("Mae =", mean_absolute_error(y_test, y_pred))
print("r2_score=",r2_score(y_test,y_pred)*100)

MSE = 76637960.25239436
Mae = 7483.592835732454
r2_score= 49.52025003617988

In [28]:
e=ElasticNet(alpha=1.0,l1_ratio=1)
e.fit(x_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.572e+09, tolerance: 3.044e+06
  model = cd_fast.enet_coordinate_descent(

ElasticNet(l1_ratio=1)

In [29]:
y_pred = e.predict(x_test)

print("MSE =", mean_squared_error(y_test, y_pred))
print("Mae =", mean_absolute_error(y_test, y_pred))
print("r2_score=",r2_score(y_test,y_pred)*100)

MSE = 76173369.23271242
Mae = 7477.9664969776295
r2_score= 49.82626599004588