In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

le=LabelEncoder()
df=pd.read_csv(r"C:\Users\CHAIT\OneDrive\Desktop\TE\Machine Learning\Dataset\employee_promotion.csv")

In [2]:
df.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Department,Gender,Promotion
0,28,132612,9,2,1,Data Engineer,High School,Seattle,IT,Male,Got Promotion
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,Analytics,Female,No Promotion
2,36,113811,11,1,6,Web Developer,PhD,Chicago,IT,Male,Got Promotion
3,32,102160,2,2,6,Data Engineer,High School,Austin,IT,Female,No Promotion
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,Management,Male,No Promotion

In [3]:
#le.fit(df['Promotion'])
#df['Promotion']=le.transform(df['Promotion'])

In [4]:
df.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Department,Gender,Promotion
0,28,132612,9,2,1,Data Engineer,High School,Seattle,IT,Male,Got Promotion
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,Analytics,Female,No Promotion
2,36,113811,11,1,6,Web Developer,PhD,Chicago,IT,Male,Got Promotion
3,32,102160,2,2,6,Data Engineer,High School,Austin,IT,Female,No Promotion
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,Management,Male,No Promotion

In [5]:
df['encoded_promotion']=le.fit_transform(df['Promotion'])
df.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Department,Gender,Promotion,encoded_promotion
0,28,132612,9,2,1,Data Engineer,High School,Seattle,IT,Male,Got Promotion,0
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,Analytics,Female,No Promotion,1
2,36,113811,11,1,6,Web Developer,PhD,Chicago,IT,Male,Got Promotion,0
3,32,102160,2,2,6,Data Engineer,High School,Austin,IT,Female,No Promotion,1
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,Management,Male,No Promotion,1

In [6]:
df['Education'].value_counts()

Education
Bachelor's     6
Master's       5
High School    4
PhD            3
MBA            2
Name: count, dtype: int64

In [7]:
dict={'High School':0,"Bachelor's":1,"Master's":2,'MBA':3,'PhD':4}
df['encoded2']=df['Education'].map(dict)
df.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Department,Gender,Promotion,encoded_promotion,encoded2
0,28,132612,9,2,1,Data Engineer,High School,Seattle,IT,Male,Got Promotion,0,0
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,Analytics,Female,No Promotion,1,2
2,36,113811,11,1,6,Web Developer,PhD,Chicago,IT,Male,Got Promotion,0,4
3,32,102160,2,2,6,Data Engineer,High School,Austin,IT,Female,No Promotion,1,0
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,Management,Male,No Promotion,1,1

In [8]:
encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(df[['City']])
print(encoded)

[[0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]]

In [9]:
df.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Department,Gender,Promotion,encoded_promotion,encoded2
0,28,132612,9,2,1,Data Engineer,High School,Seattle,IT,Male,Got Promotion,0,0
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,Analytics,Female,No Promotion,1,2
2,36,113811,11,1,6,Web Developer,PhD,Chicago,IT,Male,Got Promotion,0,4
3,32,102160,2,2,6,Data Engineer,High School,Austin,IT,Female,No Promotion,1,0
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,Management,Male,No Promotion,1,1

In [10]:
job_count=df['JobTitle'].value_counts().to_dict()
df['Job_encoded']=df['JobTitle'].map(job_count)
print(df[['JobTitle','Job_encoded']])

            JobTitle  Job_encoded
0      Data Engineer            4
1     Data Scientist            3
2      Web Developer            2
3      Data Engineer            4
4    Product Manager            2
5     Data Scientist            3
6   Business Analyst            3
7        ML Engineer            3
8      Web Developer            2
9      Data Engineer            4
10   Product Manager            2
11  Business Analyst            3
12            Intern            2
13       ML Engineer            3
14    Data Scientist            3
15          Director            1
16     Data Engineer            4
17            Intern            2
18       ML Engineer            3
19  Business Analyst            3

In [11]:
df.head()

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Department,Gender,Promotion,encoded_promotion,encoded2,Job_encoded
0,28,132612,9,2,1,Data Engineer,High School,Seattle,IT,Male,Got Promotion,0,0,4
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,Analytics,Female,No Promotion,1,2,3
2,36,113811,11,1,6,Web Developer,PhD,Chicago,IT,Male,Got Promotion,0,4,2
3,32,102160,2,2,6,Data Engineer,High School,Austin,IT,Female,No Promotion,1,0,4
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,Management,Male,No Promotion,1,1,2

In [12]:
group=df.groupby('Education')['encoded_promotion'].mean().to_dict()
print(group)
df['Education_target_encoding']=df['Education'].map(group)
df.head()

{"Bachelor's": 0.8333333333333334, 'High School': 0.75, 'MBA': 0.0, "Master's": 0.2, 'PhD': 0.0}

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Department,Gender,Promotion,encoded_promotion,encoded2,Job_encoded,Education_target_encoding
0,28,132612,9,2,1,Data Engineer,High School,Seattle,IT,Male,Got Promotion,0,0,4,0.750000
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,Analytics,Female,No Promotion,1,2,3,0.200000
2,36,113811,11,1,6,Web Developer,PhD,Chicago,IT,Male,Got Promotion,0,4,2,0.000000
3,32,102160,2,2,6,Data Engineer,High School,Austin,IT,Female,No Promotion,1,0,4,0.750000
4,29,101313,7,4,7,Product Manager,Bachelor's,San Francisco,Management,Male,No Promotion,1,1,2,0.833333