In [1]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [2]:
df=sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
df['age']=df['age'].fillna(df['age'].mean())

In [6]:
df['embarked']=df['embarked'].fillna(df['embarked'].mode()[0])

In [7]:
df=df.drop(columns=['deck','embark_town','who'],axis=1)

In [8]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,no,True

In [9]:
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])

In [10]:
df['embarked']=le.fit_transform(df['embarked'])
df['class']=le.fit_transform(df['class'])

In [13]:
df['alive']=df['alive'].map({'no':0,'yes':1})
df=df.astype(int)

In [14]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,alive,alone
0,0,3,1,22,1,0,7,2,2,1,0,0
1,1,1,0,38,1,0,71,0,0,0,1,0
2,1,3,0,26,0,0,7,2,2,0,1,1
3,1,1,0,35,1,0,53,2,0,0,1,0
4,0,3,1,35,0,0,8,2,2,1,0,1