In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df=sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.drop(['sibsp','parch','embark_town','who','adult_male','deck','class'],axis=1,inplace=True)

In [4]:
df.head(1)

   survived  pclass   sex   age  fare embarked alive  alone
0         0       3  male  22.0  7.25        S    no  False

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

In [6]:
model=KNeighborsClassifier(n_neighbors=5)

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])

In [9]:
df['embarked']=le.fit_transform(df['embarked'])

In [10]:
df.head(2)

   survived  pclass  sex   age     fare  embarked alive  alone
0         0       3    1  22.0   7.2500         2    no  False
1         1       1    0  38.0  71.2833         0   yes  False

In [11]:
df['alive']=df['alive'].map({'yes':1,'no':0})

In [12]:
df['age']=df['age'].fillna(df['age'].mean())
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    int64
 3   age       891 non-null    float64
 4   fare      891 non-null    float64
 5   embarked  891 non-null    int64
 6   alive     891 non-null    int64
 7   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(5)
memory usage: 49.7 KB

   survived  pclass  sex   age     fare  embarked  alive  alone
0         0       3    1  22.0   7.2500         2      0  False
1         1       1    0  38.0  71.2833         0      1  False
2         1       3    0  26.0   7.9250         2      1   True
3         1       1    0  35.0  53.1000         2      1  False
4         0       3    1  35.0   8.0500         2      0   True

In [13]:
df=df.astype(int)

In [14]:
df.head()

   survived  pclass  sex  age  fare  embarked  alive  alone
0         0       3    1   22     7         2      0      0
1         1       1    0   38    71         0      1      0
2         1       3    0   26     7         2      1      1
3         1       1    0   35    53         2      1      0
4         0       3    1   35     8         2      0      1

In [15]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [16]:
nv=GaussianNB()

In [17]:
x=df.drop(columns=['survived','alive'],axis=1)
y=df['survived']
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [18]:
nv.fit(x_train,y_train)

GaussianNB()

In [19]:
y_pred_nv=nv.predict(x_test)

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(y_test,y_pred_nv)*100

76.53631284916202