In [1]:
import pandas as pd
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [2]:
df=sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.info()
df['class'].unique

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

<bound method Series.unique of 0       Third
1       First
2       Third
3       First
4       Third
        ...
886    Second
887     First
888     Third
889     First
890     Third
Name: class, Length: 891, dtype: category
Categories (3, object): ['First', 'Second', 'Third']>

In [5]:
df['age']=df['age'].fillna(df['age'].mean())

In [6]:
#df=df.dropna(how='any',axis=0)

In [7]:
df=df.drop(columns=['alive','who','embark_town','deck'],axis=1)

In [8]:
df['class'].unique

<bound method Series.unique of 0       Third
1       First
2       Third
3       First
4       Third
        ...
886    Second
887     First
888     Third
889     First
890     Third
Name: class, Length: 891, dtype: category
Categories (3, object): ['First', 'Second', 'Third']>

In [9]:
df.head(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,alone
0,0,3,male,22.0,1,0,7.25,S,Third,True,False

In [10]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder

In [11]:
on=OneHotEncoder(sparse_output=False)

en=on.fit_transform(df[['embarked']])

In [12]:
en_df=pd.DataFrame(en,columns=on.get_feature_names_out(['embarked']))

In [13]:
en_df.head()

   embarked_C  embarked_Q  embarked_S  embarked_nan
0         0.0         0.0         1.0           0.0
1         1.0         0.0         0.0           0.0
2         0.0         0.0         1.0           0.0
3         0.0         0.0         1.0           0.0
4         0.0         0.0         1.0           0.0

In [14]:
df=pd.concat([df,en_df],axis=1)

In [15]:
df=df.reset_index(drop=True)
df=df.drop(['embarked'],axis=1)
df['sex']=df['sex'].map({'female':0,'male':1})
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,class,adult_male,alone,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0,3,1,22.000000,1,0,7.2500,Third,True,False,0.0,0.0,1.0,0.0
1,1,1,0,38.000000,1,0,71.2833,First,False,False,1.0,0.0,0.0,0.0
2,1,3,0,26.000000,0,0,7.9250,Third,False,True,0.0,0.0,1.0,0.0
3,1,1,0,35.000000,1,0,53.1000,First,False,False,0.0,0.0,1.0,0.0
4,0,3,1,35.000000,0,0,8.0500,Third,True,True,0.0,0.0,1.0,0.0
5,0,3,1,29.699118,0,0,8.4583,Third,True,True,0.0,1.0,0.0,0.0
6,0,1,1,54.000000,0,0,51.8625,First,True,True,0.0,0.0,1.0,0.0
7,0,3,1,2.000000,3,1,21.0750,Third,False,False,0.0,0.0,1.0,0.0
8,1,3,0,27.000000,0,2,11.1333,Third,False,False,0.0,0.0,1.0,0.0
9,1,2,0,14.000000,1,0,30.0708,Second,False,False,1.0,0.0,0.0,0.0

In [16]:
o=OrdinalEncoder(categories=[['Third','Second','First']],handle_unknown='use_encoded_value',unknown_value=-1)

In [17]:
en_df=o.fit_transform(df[['class']])

In [18]:
df['class']=pd.DataFrame(en_df,columns=o.get_feature_names_out(['class']))

In [19]:
df=df.astype(int)

In [20]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,adult_male,alone,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0,3,1,22,1,0,7,0,1,0,0,0,1,0
1,1,1,0,38,1,0,71,2,0,0,1,0,0,0
2,1,3,0,26,0,0,7,0,0,1,0,0,1,0
3,1,1,0,35,1,0,53,2,0,0,0,0,1,0
4,0,3,1,35,0,0,8,0,1,1,0,0,1,0

In [21]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc=StandardScaler()
df=sc.fit_transform(df[''])

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [25]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,-0.789272,0.827377,0.737695,-0.580044,0.432793,-0.473674,-0.498948,-0.827377,0.811922,-1.231645,-0.482043,-0.307562,0.619306,-0.047431
1,1.266990,-1.566107,-1.355574,0.650112,0.432793,-0.473674,0.789405,1.566107,-1.231645,-1.231645,2.074505,-0.307562,-1.614710,-0.047431
2,1.266990,0.827377,-1.355574,-0.272505,-0.474545,-0.473674,-0.498948,-0.827377,-1.231645,0.811922,-0.482043,-0.307562,0.619306,-0.047431
3,1.266990,-1.566107,-1.355574,0.419458,0.432793,-0.473674,0.427056,1.566107,-1.231645,-1.231645,-0.482043,-0.307562,0.619306,-0.047431
4,-0.789272,0.827377,0.737695,0.419458,-0.474545,-0.473674,-0.478817,-0.827377,0.811922,0.811922,-0.482043,-0.307562,0.619306,-0.047431