In [1]:
import pandas as pd
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [2]:
df=sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
df=df.drop(columns=['alive','who','embark_town'],axis=1)

In [6]:
df['embarked'].describe()

count     889
unique      3
top         S
freq      644
Name: embarked, dtype: object

In [8]:
df.head(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,alone
0,0,3,male,22.0,1,0,7.25,S,Third,True,NaN,False

In [9]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [15]:
on=OneHotEncoder(sparse_output=False)

en=on.fit_transform(df[['embarked']])

In [21]:
en_df=pd.DataFrame(en,columns=on.get_feature_names_out(['embarked']))

In [22]:
en_df

     embarked_C  embarked_Q  embarked_S  embarked_nan
0           0.0         0.0         1.0           0.0
1           1.0         0.0         0.0           0.0
2           0.0         0.0         1.0           0.0
3           0.0         0.0         1.0           0.0
4           0.0         0.0         1.0           0.0
..          ...         ...         ...           ...
886         0.0         0.0         1.0           0.0
887         0.0         0.0         1.0           0.0
888         0.0         0.0         1.0           0.0
889         1.0         0.0         0.0           0.0
890         0.0         1.0         0.0           0.0

[891 rows x 4 columns]